server.port=8080

spring.application.name=agentic-ai-poc
spring.threads.virtual.enabled=true

# OpenAI API key
openai.api-key=ADD YOUR KEY
openai.model=${OPENAI_MODEL:gpt-4o-mini}
openai.base-url=https://api.openai.com/v1

# Google Gemini API key and configuration
gemini.api-key=ADD YOUR KEY
gemini.model=${GEMINI_MODEL:Gemini 3.1 Pro}
gemini.base-url=https://generativelanguage.googleapis.com/v1beta/models

logging.level.com.example.agenticai=DEBUG
logging.level.io.netty.util.internal=OFF
